chore(actions): enforce ubuntu-latest runners

diff --git a/.github/workflows/eval.yml b/.github/workflows/eval.yml
--- a/.github/workflows/eval.yml
+++ b/.github/workflows/eval.yml
@@ -1,275 +1,213 @@
 name: Eval
-
 on:
   pull_request:
     paths:
-      - .github/workflows/eval.yml
-      - .github/workflows/reviews.yml # needs eval results from the same event type
-  pull_request_target:
+    - .github/workflows/eval.yml
+    - .github/workflows/reviews.yml
+  pull_request_target: null
   push:
-    # Keep this synced with ci/request-reviews/dev-branches.txt
     branches:
-      - master
-      - staging
-      - release-*
-      - staging-*
-      - haskell-updates
-      - python-updates
-
+    - master
+    - staging
+    - release-*
+    - staging-*
+    - haskell-updates
+    - python-updates
 permissions: {}
-
 jobs:
   prepare:
     name: Prepare
-    runs-on: ubuntu-24.04-arm
+    runs-on: ubuntu-latest
     outputs:
       mergedSha: ${{ steps.get-merge-commit.outputs.mergedSha }}
       targetSha: ${{ steps.get-merge-commit.outputs.targetSha }}
       systems: ${{ steps.systems.outputs.systems }}
     steps:
-      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
-        with:
-          sparse-checkout: |
-            .github/actions
-            ci/supportedSystems.json
-      - name: Check if the PR can be merged and get the test merge commit
-        uses: ./.github/actions/get-merge-commit
-        id: get-merge-commit
+    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
+      with:
+        sparse-checkout: '.github/actions
 
-      - name: Load supported systems
-        id: systems
-        run: |
-          echo "systems=$(jq -c <ci/supportedSystems.json)" >> "$GITHUB_OUTPUT"
+          ci/supportedSystems.json
 
+          '
+    - name: Check if the PR can be merged and get the test merge commit
+      uses: ./.github/actions/get-merge-commit
+      id: get-merge-commit
+    - name: Load supported systems
+      id: systems
+      run: 'echo "systems=$(jq -c <ci/supportedSystems.json)" >> "$GITHUB_OUTPUT"
+
+        '
   outpaths:
     name: Outpaths
-    runs-on: ubuntu-24.04-arm
-    needs: [ prepare ]
+    runs-on: ubuntu-latest
+    needs:
+    - prepare
     strategy:
       fail-fast: false
       matrix:
         system: ${{ fromJSON(needs.prepare.outputs.systems) }}
     steps:
-      - name: Enable swap
-        run: |
-          sudo fallocate -l 10G /swap
-          sudo chmod 600 /swap
-          sudo mkswap /swap
-          sudo swapon /swap
+    - name: Enable swap
+      run: 'sudo fallocate -l 10G /swap
 
-      - name: Check out the PR at the test merge commit
-        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
-        with:
-          ref: ${{ needs.prepare.outputs.mergedSha }}
-          path: untrusted
+        sudo chmod 600 /swap
 
-      - name: Install Nix
-        uses: cachix/install-nix-action@526118121621777ccd86f79b04685a9319637641 # v31
-        with:
-          extra_nix_config: sandbox = true
+        sudo mkswap /swap
 
-      - name: Evaluate the ${{ matrix.system }} output paths for all derivation attributes
-        env:
-          MATRIX_SYSTEM: ${{ matrix.system }}
-        run: |
-          nix-build untrusted/ci -A eval.singleSystem \
-            --argstr evalSystem "$MATRIX_SYSTEM" \
-            --arg chunkSize 10000 \
-            --out-link merged
-          # If it uses too much memory, slightly decrease chunkSize
+        sudo swapon /swap
 
-      - name: Upload the output paths and eval stats
-        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
-        with:
-          name: merged-${{ matrix.system }}
-          path: merged/*
-
-      - name: Get target run id
-        if: needs.prepare.outputs.targetSha
-        id: targetRunId
-        env:
-          GH_TOKEN: ${{ github.token }}
-          MATRIX_SYSTEM: ${{ matrix.system }}
-          REPOSITORY: ${{ github.repository }}
-          TARGET_SHA: ${{ needs.prepare.outputs.targetSha }}
-        run: |
-          # Get the latest eval.yml workflow run for the PR's target commit
-          if ! run=$(gh api --method GET /repos/"$REPOSITORY"/actions/workflows/eval.yml/runs \
-            -f head_sha="$TARGET_SHA" -f event=push \
-            --jq '.workflow_runs | sort_by(.run_started_at) | .[-1]') \
-            || [[ -z "$run" ]]; then
-            echo "Could not find an eval.yml workflow run for $TARGET_SHA, cannot make comparison"
-            exit 1
-          fi
-          echo "Comparing against $(jq .html_url <<< "$run")"
-          runId=$(jq .id <<< "$run")
-
-          if ! job=$(gh api --method GET /repos/"$REPOSITORY"/actions/runs/"$runId"/jobs \
-            --jq ".jobs[] | select (.name == \"Outpaths ($MATRIX_SYSTEM)\")") \
-            || [[ -z "$job" ]]; then
-            echo "Could not find the Outpaths ($MATRIX_SYSTEM) job for workflow run $runId, cannot make comparison"
-            exit 1
-          fi
-          jobId=$(jq .id <<< "$job")
-          conclusion=$(jq -r .conclusion <<< "$job")
-
-          while [[ "$conclusion" == null || "$conclusion" == "" ]]; do
-            echo "Job not done, waiting 10 seconds before checking again"
-            sleep 10
-            conclusion=$(gh api /repos/"$REPOSITORY"/actions/jobs/"$jobId" --jq '.conclusion')
-          done
-
-          if [[ "$conclusion" != "success" ]]; then
-            echo "Job was not successful (conclusion: $conclusion), cannot make comparison"
-            exit 1
-          fi
-
-          echo "targetRunId=$runId" >> "$GITHUB_OUTPUT"
-
-      - uses: actions/download-artifact@v4
-        if: steps.targetRunId.outputs.targetRunId
-        with:
-          run-id: ${{ steps.targetRunId.outputs.targetRunId }}
-          name: merged-${{ matrix.system }}
-          path: target
-          github-token: ${{ github.token }}
-          merge-multiple: true
-
-      - name: Compare outpaths against the target branch
-        if: steps.targetRunId.outputs.targetRunId
-        env:
-          MATRIX_SYSTEM: ${{ matrix.system }}
-        run: |
-          nix-build untrusted/ci -A eval.diff \
-            --arg beforeDir ./target \
-            --arg afterDir "$(readlink ./merged)" \
-            --argstr evalSystem "$MATRIX_SYSTEM" \
-            --out-link diff
-
-      - name: Upload outpaths diff and stats
-        if: steps.targetRunId.outputs.targetRunId
-        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
-        with:
-          name: diff-${{ matrix.system }}
-          path: diff/*
-
+        '
+    - name: Check out the PR at the test merge commit
+      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
+      with:
+        ref: ${{ needs.prepare.outputs.mergedSha }}
+        path: untrusted
+    - name: Install Nix
+      uses: cachix/install-nix-action@526118121621777ccd86f79b04685a9319637641
+      with:
+        extra_nix_config: sandbox = true
+    - name: Evaluate the ${{ matrix.system }} output paths for all derivation attributes
+      env:
+        MATRIX_SYSTEM: ${{ matrix.system }}
+      run: "nix-build untrusted/ci -A eval.singleSystem \\\n  --argstr evalSystem\
+        \ \"$MATRIX_SYSTEM\" \\\n  --arg chunkSize 10000 \\\n  --out-link merged\n\
+        # If it uses too much memory, slightly decrease chunkSize\n"
+    - name: Upload the output paths and eval stats
+      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
+      with:
+        name: merged-${{ matrix.system }}
+        path: merged/*
+    - name: Get target run id
+      if: needs.prepare.outputs.targetSha
+      id: targetRunId
+      env:
+        GH_TOKEN: ${{ github.token }}
+        MATRIX_SYSTEM: ${{ matrix.system }}
+        REPOSITORY: ${{ github.repository }}
+        TARGET_SHA: ${{ needs.prepare.outputs.targetSha }}
+      run: "# Get the latest eval.yml workflow run for the PR's target commit\nif\
+        \ ! run=$(gh api --method GET /repos/\"$REPOSITORY\"/actions/workflows/eval.yml/runs\
+        \ \\\n  -f head_sha=\"$TARGET_SHA\" -f event=push \\\n  --jq '.workflow_runs\
+        \ | sort_by(.run_started_at) | .[-1]') \\\n  || [[ -z \"$run\" ]]; then\n\
+        \  echo \"Could not find an eval.yml workflow run for $TARGET_SHA, cannot\
+        \ make comparison\"\n  exit 1\nfi\necho \"Comparing against $(jq .html_url\
+        \ <<< \"$run\")\"\nrunId=$(jq .id <<< \"$run\")\n\nif ! job=$(gh api --method\
+        \ GET /repos/\"$REPOSITORY\"/actions/runs/\"$runId\"/jobs \\\n  --jq \".jobs[]\
+        \ | select (.name == \\\"Outpaths ($MATRIX_SYSTEM)\\\")\") \\\n  || [[ -z\
+        \ \"$job\" ]]; then\n  echo \"Could not find the Outpaths ($MATRIX_SYSTEM)\
+        \ job for workflow run $runId, cannot make comparison\"\n  exit 1\nfi\njobId=$(jq\
+        \ .id <<< \"$job\")\nconclusion=$(jq -r .conclusion <<< \"$job\")\n\nwhile\
+        \ [[ \"$conclusion\" == null || \"$conclusion\" == \"\" ]]; do\n  echo \"\
+        Job not done, waiting 10 seconds before checking again\"\n  sleep 10\n  conclusion=$(gh\
+        \ api /repos/\"$REPOSITORY\"/actions/jobs/\"$jobId\" --jq '.conclusion')\n\
+        done\n\nif [[ \"$conclusion\" != \"success\" ]]; then\n  echo \"Job was not\
+        \ successful (conclusion: $conclusion), cannot make comparison\"\n  exit 1\n\
+        fi\n\necho \"targetRunId=$runId\" >> \"$GITHUB_OUTPUT\"\n"
+    - uses: actions/download-artifact@v4
+      if: steps.targetRunId.outputs.targetRunId
+      with:
+        run-id: ${{ steps.targetRunId.outputs.targetRunId }}
+        name: merged-${{ matrix.system }}
+        path: target
+        github-token: ${{ github.token }}
+        merge-multiple: true
+    - name: Compare outpaths against the target branch
+      if: steps.targetRunId.outputs.targetRunId
+      env:
+        MATRIX_SYSTEM: ${{ matrix.system }}
+      run: "nix-build untrusted/ci -A eval.diff \\\n  --arg beforeDir ./target \\\n\
+        \  --arg afterDir \"$(readlink ./merged)\" \\\n  --argstr evalSystem \"$MATRIX_SYSTEM\"\
+        \ \\\n  --out-link diff\n"
+    - name: Upload outpaths diff and stats
+      if: steps.targetRunId.outputs.targetRunId
+      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
+      with:
+        name: diff-${{ matrix.system }}
+        path: diff/*
   compare:
     name: Comparison
-    runs-on: ubuntu-24.04-arm
-    needs: [ prepare, outpaths ]
+    runs-on: ubuntu-latest
+    needs:
+    - prepare
+    - outpaths
     if: needs.prepare.outputs.targetSha
     permissions:
-      issues: write # needed to create *new* labels
+      issues: write
       pull-requests: write
       statuses: write
     steps:
-      - name: Download output paths and eval stats for all systems
-        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
-        with:
-          pattern: diff-*
-          path: diff
-          merge-multiple: true
-
-      - name: Check out the PR at the target commit
-        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
-        with:
-          ref: ${{ needs.prepare.outputs.targetSha }}
-          path: trusted
-
-      - name: Install Nix
-        uses: cachix/install-nix-action@526118121621777ccd86f79b04685a9319637641 # v31
-        with:
-          extra_nix_config: sandbox = true
-
-      - name: Combine all output paths and eval stats
-        run: |
-          nix-build trusted/ci -A eval.combine \
-            --arg diffDir ./diff \
-            --out-link combined
-
-      - name: Compare against the target branch
-        env:
-          AUTHOR_ID: ${{ github.event.pull_request.user.id }}
-        run: |
-          git -C trusted fetch --depth 1 origin ${{ needs.prepare.outputs.mergedSha }}
-          git -C trusted diff --name-only ${{ needs.prepare.outputs.mergedSha }} \
-            | jq --raw-input --slurp 'split("\n")[:-1]' > touched-files.json
-
-          # Use the target branch to get accurate maintainer info
-          nix-build trusted/ci -A eval.compare \
-            --arg combinedDir "$(realpath ./combined)" \
-            --arg touchedFilesJson ./touched-files.json \
-            --argstr githubAuthorId "$AUTHOR_ID" \
-            --out-link comparison
-
-          cat comparison/step-summary.md >> "$GITHUB_STEP_SUMMARY"
-
-      - name: Upload the comparison results
-        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
-        with:
-          name: comparison
-          path: comparison/*
-
-      - name: Labelling pull request
-        if: ${{ github.event_name == 'pull_request_target' }}
-        env:
-          GH_TOKEN: ${{ github.token }}
-          REPOSITORY: ${{ github.repository }}
-          NUMBER: ${{ github.event.number }}
-        run: |
-          # Get all currently set labels that we manage
-          gh api \
-            /repos/"$REPOSITORY"/issues/"$NUMBER"/labels \
-            --jq '.[].name | select(startswith("10.rebuild") or . == "11.by: package-maintainer")' \
-            | sort > before
-
-          # And the labels that should be there
-          jq -r '.labels[]' comparison/changed-paths.json \
-            | sort > after
-
-          # Remove the ones not needed anymore
-          while read -r toRemove; do
-            echo "Removing label $toRemove"
-            gh api \
-              --method DELETE \
-              /repos/"$REPOSITORY"/issues/"$NUMBER"/labels/"$toRemove"
-          done < <(comm -23 before after)
-
-          # And add the ones that aren't set already
-          while read -r toAdd; do
-            echo "Adding label $toAdd"
-            gh api \
-              --method POST \
-              /repos/"$REPOSITORY"/issues/"$NUMBER"/labels \
-              -f "labels[]=$toAdd"
-          done < <(comm -13 before after)
-
-      - name: Add eval summary to commit statuses
-        if: ${{ github.event_name == 'pull_request_target' }}
-        env:
-          GH_TOKEN: ${{ github.token }}
-          PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
-          NUMBER: ${{ github.event.number }}
-        run: |
-          description=$(jq -r '
-          "Package: added " + (.attrdiff.added | length | tostring) +
-          ", removed " + (.attrdiff.removed | length | tostring) +
-          ", changed " + (.attrdiff.changed | length | tostring) +
-          ", Rebuild: linux " + (.rebuildCountByKernel.linux | tostring) +
-          ", darwin " + (.rebuildCountByKernel.darwin | tostring)
-          ' <comparison/changed-paths.json)
-          target_url="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID?pr=$NUMBER"
-          gh api --method POST \
-            -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" \
-            "/repos/$GITHUB_REPOSITORY/statuses/$PR_HEAD_SHA" \
-            -f "context=Eval / Summary" -f "state=success" -f "description=$description" -f "target_url=$target_url"
-
+    - name: Download output paths and eval stats for all systems
+      uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16
+      with:
+        pattern: diff-*
+        path: diff
+        merge-multiple: true
+    - name: Check out the PR at the target commit
+      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
+      with:
+        ref: ${{ needs.prepare.outputs.targetSha }}
+        path: trusted
+    - name: Install Nix
+      uses: cachix/install-nix-action@526118121621777ccd86f79b04685a9319637641
+      with:
+        extra_nix_config: sandbox = true
+    - name: Combine all output paths and eval stats
+      run: "nix-build trusted/ci -A eval.combine \\\n  --arg diffDir ./diff \\\n \
+        \ --out-link combined\n"
+    - name: Compare against the target branch
+      env:
+        AUTHOR_ID: ${{ github.event.pull_request.user.id }}
+      run: "git -C trusted fetch --depth 1 origin ${{ needs.prepare.outputs.mergedSha\
+        \ }}\ngit -C trusted diff --name-only ${{ needs.prepare.outputs.mergedSha\
+        \ }} \\\n  | jq --raw-input --slurp 'split(\"\\n\")[:-1]' > touched-files.json\n\
+        \n# Use the target branch to get accurate maintainer info\nnix-build trusted/ci\
+        \ -A eval.compare \\\n  --arg combinedDir \"$(realpath ./combined)\" \\\n\
+        \  --arg touchedFilesJson ./touched-files.json \\\n  --argstr githubAuthorId\
+        \ \"$AUTHOR_ID\" \\\n  --out-link comparison\n\ncat comparison/step-summary.md\
+        \ >> \"$GITHUB_STEP_SUMMARY\"\n"
+    - name: Upload the comparison results
+      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
+      with:
+        name: comparison
+        path: comparison/*
+    - name: Labelling pull request
+      if: ${{ github.event_name == 'pull_request_target' }}
+      env:
+        GH_TOKEN: ${{ github.token }}
+        REPOSITORY: ${{ github.repository }}
+        NUMBER: ${{ github.event.number }}
+      run: "# Get all currently set labels that we manage\ngh api \\\n  /repos/\"\
+        $REPOSITORY\"/issues/\"$NUMBER\"/labels \\\n  --jq '.[].name | select(startswith(\"\
+        10.rebuild\") or . == \"11.by: package-maintainer\")' \\\n  | sort > before\n\
+        \n# And the labels that should be there\njq -r '.labels[]' comparison/changed-paths.json\
+        \ \\\n  | sort > after\n\n# Remove the ones not needed anymore\nwhile read\
+        \ -r toRemove; do\n  echo \"Removing label $toRemove\"\n  gh api \\\n    --method\
+        \ DELETE \\\n    /repos/\"$REPOSITORY\"/issues/\"$NUMBER\"/labels/\"$toRemove\"\
+        \ndone < <(comm -23 before after)\n\n# And add the ones that aren't set already\n\
+        while read -r toAdd; do\n  echo \"Adding label $toAdd\"\n  gh api \\\n   \
+        \ --method POST \\\n    /repos/\"$REPOSITORY\"/issues/\"$NUMBER\"/labels \\\
+        \n    -f \"labels[]=$toAdd\"\ndone < <(comm -13 before after)\n"
+    - name: Add eval summary to commit statuses
+      if: ${{ github.event_name == 'pull_request_target' }}
+      env:
+        GH_TOKEN: ${{ github.token }}
+        PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
+        NUMBER: ${{ github.event.number }}
+      run: "description=$(jq -r '\n\"Package: added \" + (.attrdiff.added | length\
+        \ | tostring) +\n\", removed \" + (.attrdiff.removed | length | tostring)\
+        \ +\n\", changed \" + (.attrdiff.changed | length | tostring) +\n\", Rebuild:\
+        \ linux \" + (.rebuildCountByKernel.linux | tostring) +\n\", darwin \" + (.rebuildCountByKernel.darwin\
+        \ | tostring)\n' <comparison/changed-paths.json)\ntarget_url=\"$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID?pr=$NUMBER\"\
+        \ngh api --method POST \\\n  -H \"Accept: application/vnd.github+json\" -H\
+        \ \"X-GitHub-Api-Version: 2022-11-28\" \\\n  \"/repos/$GITHUB_REPOSITORY/statuses/$PR_HEAD_SHA\"\
+        \ \\\n  -f \"context=Eval / Summary\" -f \"state=success\" -f \"description=$description\"\
+        \ -f \"target_url=$target_url\"\n"
   reviewers:
     name: Reviewers
-    # No dependency on "compare", so that it can start at the same time.
-    # We only wait for the "comparison" artifact to be available, which makes the start-to-finish time
-    # for the eval workflow considerably faster.
-    needs: [ prepare, outpaths ]
+    needs:
+    - prepare
+    - outpaths
     if: needs.prepare.outputs.targetSha
     uses: ./.github/workflows/reviewers.yml
     secrets: inherit
